from pathlib import Path
p=Path('src/style.css');s=p.read_text(encoding='utf-8')
changes=[
('.product-section{padding:0 3.5% 15px;position:relative}', '.product-section{padding:0 3.5% 52px;position:relative}'),
('.collection-tile{height:clamp(168px,24vw,346px);padding:0;border:1.5px solid #6558ff;background:white;border-radius:27px;', '.collection-tile{height:clamp(168px,24vw,346px);padding:0;border:1.5px solid #6558ff;background:white;border-radius:35px;'),
('.best-section{position:relative;padding:3px 4% 199px}', '.best-section{position:relative;padding:0 4% 199px}'),
('.back-pill{position:relative;z-index:3;margin:27px 0 0 3.5%;height:80px;border:0;background:#0037d8;color:#fff;border-radius:50px;padding:0 19px;display:flex;align-items:center;gap:8px;font:44px var(--display)}.detail-page', '.back-pill{position:relative;z-index:3;margin:27px 0 0 3.5%;height:80px;border:0;background:#0037d8;color:#fff;border-radius:50px;padding:0 19px;display:flex;align-items:center;gap:8px;font:44px var(--display)}.detail-page'),
('.cart-panel{position:relative;z-index:1;margin:24px 3.5% 0;min-height:640px;border-radius:48px;background:linear-gradient(110deg,#cdd8ffde,#cbd2f1bb);backdrop-filter:blur(16px);display:grid;grid-template-columns:1fr 1fr;padding:55px 8%;gap:4%;align-items:center}', '.cart-panel{position:relative;z-index:1;margin:24px 2.8% 0;min-height:728px;border-radius:50px;background:linear-gradient(110deg,#cdd8ffde,#cbd2f1bb);backdrop-filter:blur(16px);display:grid;grid-template-columns:40% 60%;padding:55px 0;gap:0;align-items:center}'),
('.cart-list{display:flex;flex-direction:column;gap:16px}', '.cart-list{display:flex;flex-direction:column;gap:0;padding-left:17.5%;padding-right:6%;transform:translateY(48px)}'),
('.cart-list article{height:120px;background:#fff;border-radius:50px;display:flex;align-items:center;padding:10px 17px;gap:20px;position:relative}', '.cart-list article{height:153px;background:#fff;border-radius:55px;display:flex;align-items:center;padding:8px 23px;gap:20px;position:relative}.cart-list article + article{margin-top:52px}'),
('.cart-list article img{width:80px;height:98px;object-fit:cover;border-radius:18px}', '.cart-list article img{width:127px;height:137px;object-fit:cover;border-radius:17px}'),
('.cart-list article div{display:grid;gap:11px;text-align:center;flex:1}', '.cart-list article div{display:grid;gap:11px;text-align:center;flex:1}'),
('.cart-list article strong{font:18px var(--display);color:#092aae}.cart-list article b{font:23px var(--display);color:#00b52c}', '.cart-list article strong{font:31px var(--display);color:#092aae}.cart-list article b{font:35px var(--display);color:#00b52c}'),
('.pay-button{align-self:flex-end;margin-left:auto;min-width:260px;height:73px;', '.pay-button{align-self:flex-end;margin:52px 0 0 auto;min-width:264px;height:74px;'),
('.profile-card{position:relative;z-index:1;margin:40px 3.5% 0;min-height:600px;border-radius:50px;background:#cbd4f6;', '.profile-card{position:relative;z-index:1;margin:40px 3.5% 0;min-height:728px;border-radius:50px;background:#cbd4f6;'),
('.profile-card{position:relative;z-index:1;margin:40px 3.5% 0;min-height:728px;border-radius:50px;background:#cbd4f6;box-shadow:inset 0 0 95px #fff7;display:flex;justify-content:center;align-items:flex-start;padding:300px 4% 90px}', '.profile-card{position:relative;z-index:1;margin:40px 3.5% 0;min-height:728px;border-radius:50px;background:#cbd4f6;box-shadow:inset 0 0 95px #fff7;display:flex;justify-content:center;align-items:flex-start;padding:315px 4% 90px}'),
('.profile-data strong{font-size:clamp(14px,2.5vw,31px);white-space:nowrap}', '.profile-data strong{font-size:clamp(14px,2.8vw,40px);white-space:nowrap}'),
('.info-mark{font:350px/1 Arial,sans-serif;transform:scaleX(1.3);text-align:center;position:relative;z-index:1}', '.info-mark{width:min(42vw,600px);height:auto;transform:none;text-align:center;position:relative;z-index:1;color:white}'),
('.faq-list h1,.faq-list h2,.support-links button{font:32px/1.45 var(--display);margin:0 0 26px}', '.faq-list h1,.faq-list h2,.support-links button{font:40px/1.3 var(--display);margin:0 0 26px}'),
('.faq-list h1{font-size:39px;margin-bottom:0}', '.faq-list h1{font-size:47px;margin-bottom:0}'),
('.faq-list h2{max-width:530px}', '.faq-list h2{max-width:530px}'),
('.detail-layout{max-width:1440px;margin:4px auto 0;', '.detail-layout{max-width:1440px;margin:-4px auto 0;'),
]
for old,new in changes:
 count=s.count(old)
 if count==1:s=s.replace(old,new,1)
 else:print('skip',count,old[:95])
s=s.replace('.about-info{display:grid;grid-template-columns:47% 53%;', '.about-info{display:grid;grid-template-columns:47% 53%;')
s += "\n.zigzag{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:0}.zigzag span{display:block;width:132px;height:118px;margin:-15px 0;background:#fff;clip-path:polygon(0 0,67% 38%,49% 51%,100% 80%,33% 100%,44% 73%,0 33%,55% 44%)}.info-mark{overflow:visible}.profile-avatar{object-position:center}.cart-alert{transform:translateY(-18px)}@media(max-width:600px){.product-section{padding-bottom:20px}.collection-tile{border-radius:14px}.cart-panel{min-height:600px;grid-template-columns:1fr;padding:26px 5%;gap:22px}.cart-list{padding:0;transform:none}.cart-list article{height:83px;border-radius:40px;padding:7px 12px;gap:10px}.cart-list article+article{margin-top:10px}.cart-list article img{height:69px;width:54px;border-radius:12px}.cart-list article strong{font-size:11px}.cart-list article b{font-size:15px}.cart-list article button{top:6px;right:7px}.pay-button{margin:0 0 0 auto;min-width:155px;height:51px;font-size:25px;border-radius:16px}.profile-card{min-height:420px;padding:185px 3% 60px}.profile-data strong{font-size:13px}.info-mark{width:72vw;height:auto;margin:auto}.faq-list h1{font-size:23px}.faq-list h2,.support-links button{font-size:13px;line-height:1.4;margin-bottom:17px}.zigzag span{width:48px;height:57px;margin:-7px 0}.auth-page{height:100svh;min-height:100svh;padding:5vh 3%}.auth-glass{height:80vh;min-height:370px;padding:25px 6%;gap:22px}.auth-login .auth-glass{padding-top:16vh}.auth-register .auth-glass{padding-top:8vh}.auth-glass input{height:56px;font-size:17px;padding:0 20px}.auth-submit{width:52%;height:57px;font-size:19px}.auth-switch{font-size:17px}}\n"
p.write_text(s,encoding='utf-8')
