<script setup lang="ts">
import { computed, ref } from 'vue'
import { ArrowLeft, ArrowRight, ChevronRight, CircleCheck, Heart, Menu, Pencil, Search, ShoppingCart, Trash2, UserRound, X } from 'lucide-vue-next'

type Screen = 'home' | 'product' | 'cart' | 'profile' | 'login' | 'register' | 'about' | 'tech' | 'collection' | 'support'
type Product = { id: number; name: string; category: string; price: number; image: string; label?: string; size: string; purpose: string; rating: string }
const products: Product[] = [
  { id: 1, name: 'Asphalt Basketball', category: 'Basketballs', price: 38945, image: '/images/collection-asphalt.png', label: 'NEW', size: '6', purpose: 'Outdoor', rating: '4.9' },
  { id: 2, name: 'Grip Basketball Socks', category: 'Accessories', price: 7000, image: '/images/collection-socks.png', label: 'BESTSELLER', size: 'M / L', purpose: 'All courts', rating: '4.9' },
  { id: 3, name: 'Pechenka Chocolate', category: 'Basketballs', price: 24990, image: '/images/collection-pechenka.png', size: '7', purpose: 'Indoor', rating: '5.0' },
  { id: 4, name: 'Wave Basketball', category: 'Basketballs', price: 30000, image: '/images/best-wave.png', label: 'NEW DROP', size: '6', purpose: 'Outdoor', rating: '4.8' },
  { id: 5, name: 'Knee Compression Sleeve', category: 'Protection', price: 9000, image: '/images/best-sleeves.png', size: 'S / M / L', purpose: 'Training', rating: '4.8' },
  { id: 6, name: 'Court Jersey', category: 'Apparel', price: 18900, image: '/images/collection-apparel.png', size: 'S / M / L', purpose: 'Training', rating: '4.7' },
]
const screen = ref<Screen>('login')
const previousScreen = ref<Screen>('home')
const selected = ref<Product>(products[0])
const cart = ref<Product[]>([products[3], products[1], products[4]])
const cartOpen = ref(false)
const paying = ref(false)
const favorites = ref<number[]>([])
const menuOpen = ref(false)
const query = ref('')
const searchOpen = ref(false)
const collectionProducts = computed(() => [products[4], products[1], products[0], products[2], products[5]].filter((p): p is Product => Boolean(p)).filter(p => p.name.toLowerCase().includes(query.value.toLowerCase())))
const fmt = (price: number) => new Intl.NumberFormat('ru-RU').format(price)
const collectionImage = (product: Product) => product.id === 5 ? '/images/collection-leggings.png' : product.id === 2 ? '/images/collection-socks.png' : product.id === 1 ? '/images/collection-asphalt.png' : product.id === 3 ? '/images/collection-pechenka.png' : product.id === 6 ? '/images/collection-apparel.png' : product.image
const cartImage = (product: Product) => product.id === 4 ? '/images/cart-wave.jpg' : product.id === 2 ? '/images/cart-socks.jpg' : product.id === 5 ? '/images/cart-sleeve.jpg' : product.image
const checkoutItems = computed(() => cart.value.length >= 3 ? [cart.value[0], cart.value[2], cart.value[1], ...cart.value.slice(3)] : cart.value)
function openProduct(product: Product) { previousScreen.value = screen.value; selected.value = product; screen.value = 'product'; window.scrollTo({ top: 0, behavior: 'smooth' }) }
function addToCart(product: Product, open = true) { cart.value.push(product); if (open) screen.value = 'cart'; window.scrollTo({ top: 0 }) }
function toggleFavorite(id: number) { favorites.value = favorites.value.includes(id) ? favorites.value.filter(item => item !== id) : [...favorites.value, id] }
function payOrder() { if (!cart.value.length) return; paying.value = true; cart.value = []; previousScreen.value = 'home'; window.setTimeout(() => { paying.value = false; screen.value = 'profile'; window.scrollTo({ top: 0 }) }, 850) }
function go(next: Screen) { previousScreen.value = screen.value; screen.value = next; menuOpen.value = false; window.scrollTo({ top: 0, behavior: 'smooth' }) }
function back() { screen.value = previousScreen.value === 'home' || previousScreen.value === 'login' ? 'home' : previousScreen.value; window.scrollTo({ top: 0, behavior: 'smooth' }) }
function scrollToProducts() { document.getElementById('new-collection')?.scrollIntoView({ behavior: 'smooth' }) }
</script>

<template>
  <div class="combasket">
    <header v-if="screen === 'home'" class="topbar">
      <button class="top-icon menu-button" aria-label="Open menu" @click="menuOpen = !menuOpen"><X v-if="menuOpen" :size="19"/><Menu v-else :size="19"/></button>
      <button class="logo" aria-label="COMBASKET home" @click="go('home')"><img class="logo-symbol" src="/images/combasket-mark-white.png" alt=""/><span>COMBASKET</span></button>
      <div class="search-box"><input v-model="query" placeholder="" aria-label="Search products" @focus="searchOpen = true" @keyup.enter="scrollToProducts()"/><button @click="scrollToProducts()"><span>Search</span><Search :size="14"/></button></div>
      <div class="top-actions"><button class="top-icon" @click="cartOpen = true"><span>Cart</span><ShoppingCart :size="18"/><b class="cart-count">{{ cart.length }}</b></button><button class="top-icon" @click="go('profile')"><span>Profile</span><UserRound :size="19"/></button></div>
      <nav v-if="menuOpen" class="menu-popover"><button @click="go('home')">Home <ChevronRight :size="15"/></button><button @click="go('collection')">Collections <ChevronRight :size="15"/></button><button @click="go('about')">About us <ChevronRight :size="15"/></button><button @click="go('tech')">Technology <ChevronRight :size="15"/></button><button @click="go('support')">Support <ChevronRight :size="15"/></button></nav>
    </header>

    <main v-if="screen === 'home'" class="home-page">
      <section class="home-hero"><div class="outline-ball ball-one"></div><div class="outline-ball ball-two"></div><div class="hero-slash"></div><div class="intro-glass"><p><strong>COMBASKET</strong> is more than just gear.<br/>We create basketballs and equipment for those who live the game — from street courts to big arenas. Reliability, control, and style are everything you need to make every shot count.</p></div><a class="hero-category" href="#new-collection">Discover the game <ArrowRight :size="16"/></a></section>

      <section id="new-collection" class="product-section"><div class="outline-ball collection-ball"></div><h1>NEW COLLECTION</h1><div class="collection-row"><button v-for="p in collectionProducts" :key="p.id" class="collection-tile" @click="openProduct(p)"><img :src="collectionImage(p)" :alt="p.name"/><span class="tile-arrow"><ArrowRight :size="16"/></span></button></div></section>

      <section class="why-section"><div class="outline-ball why-ball"></div><div class="blue-swoosh"></div><h2>Why us?</h2><div class="benefit-card benefit-a"><img class="benefit-icon" src="/images/icon-quality.png" alt=""/><p>Game-Ready<br/>Quality durable<br/>materials built for<br/>intense play</p></div><div class="benefit-card benefit-b"><img class="benefit-icon" src="/images/icon-flame.png" alt=""/><p>Superior Grip &amp;<br/>Control — precision<br/>feel in every move</p></div><div class="benefit-card benefit-c"><img class="benefit-icon" src="/images/icon-jersey.png" alt=""/><p>Street &amp; Pro<br/>Versatility perfect<br/>for outdoor and<br/>indoor courts</p></div><div class="benefit-card benefit-d"><img class="benefit-icon" src="/images/icon-basketball.png" alt=""/><p>Modern Design —<br/>clean style that<br/>stands out</p></div><div class="benefit-card benefit-e"><img class="benefit-icon" src="/images/icon-test-tube.png" alt=""/><p>Built for Players —<br/>tested and inspired<br/>by real basketball<br/>culture</p></div></section>

      <section class="best-section"><div class="best-ribbon"></div><div class="outline-ball best-ball"></div><div class="outline-ball best-ball-lower"></div><div class="outline-ball best-ball-right"></div><h2>Best Sellers</h2><div class="best-grid"><button v-for="p in [products[3], products[4], products[2]]" :key="p.id" class="best-tile" @click="openProduct(p)"><img :src="p.id === 5 ? '/images/best-sleeves.png' : p.id === 3 ? '/images/best-pechenka.png' : p.image" :alt="p.name"/><span>{{ p.name }} <ArrowRight :size="16"/></span></button></div></section>
      <footer class="store-footer"><div class="market-stats"><strong>Our market</strong><div class="stats-row"><span>Orders<br/><b>50,3K</b></span><span>Ozon<br/><b>5</b></span><span>Reviews<br/><b>13,4K</b></span><span>Wildberries<br/><b>5,11</b></span></div><div class="stats-detail"><span>Average product rating<br/><b>4,9 from 5</b></span><span>Products purchased<br/><b>82%</b></span><span>Original brand products<br/><b>TM IPP 313590629700021</b></span><span>SALED<br/><b>139 266</b></span></div></div><div class="social-block"><strong>SOCIAL NETWORKS</strong><div><a href="#instagram" aria-label="Instagram"><img src="/images/social-instagram.png" alt=""/></a><a href="#wb" aria-label="Wildberries"><img src="/images/social-wildberries.png" alt=""/></a><a href="#vk" aria-label="VK"><img src="/images/social-vk.png" alt=""/></a><a href="#ozon" aria-label="Ozon"><img src="/images/social-ozon.png" alt=""/></a></div><nav><button @click="go('support')">SUPPORT</button><button @click="go('tech')">TECHNOLOGY</button><button @click="go('collection')">COLLECTIONS</button><button @click="go('about')">ABOUT US</button></nav></div></footer>
    </main>

    <main v-else-if="screen === 'product'" class="detail-page"><button class="back-pill" @click="back"><ArrowLeft :size="22"/> BACK</button><div class="outline-ball detail-ball-top"></div><div class="outline-ball detail-ball-bottom"></div><div class="detail-layout"><div class="detail-gallery"><img :src="selected.id === 1 ? '/images/ball-detail.jpg' : selected.image" :alt="selected.name"/><div class="gallery-dots"><span class="current"></span><span></span><span></span><span></span></div><div class="stars">★★★★★</div></div><div class="detail-info"><p class="detail-kicker">COMBASKET · {{ selected.category.toUpperCase() }}</p><h1>{{ selected.id === 1 ? 'Streetball basketball' : selected.name }}<br/>Size {{ selected.size.includes(' ') ? '6' : selected.size }} for<br/>BASKETBALL</h1><p class="review-count"><b>{{ selected.rating === '4.9' ? '845' : '327' }}</b> reviews <b>137</b> questions</p><div class="spec-table"><strong>About the product</strong><strong>Go to description</strong><span>Type</span><span>Basketball</span><span>Ball Size</span><span>{{ selected.size }}</span><span>Ball Purpose</span><span>{{ selected.purpose }}</span><span>Certificate</span><span>FIBA</span><span>Country of Origin</span><span>China</span></div><button class="purchase-button" @click="addToCart(selected)"><strong>{{ fmt(selected.price) }}</strong><span>Add to cart and pay <ArrowRight :size="19"/></span></button><button class="favorite-detail" :class="{ active: favorites.includes(selected.id) }" @click="toggleFavorite(selected.id)"><Heart :size="17"/> {{ favorites.includes(selected.id) ? 'Saved to favorites' : 'Add to favorites' }}</button></div></div></main>

    <main v-else-if="screen === 'cart'" class="cart-page"><button class="back-pill" @click="go('home')"><ArrowLeft :size="22"/> BACK</button><div class="cart-panel"><div class="cart-alert"><span class="alert-icon">!</span><h1>ATTENTION!<br/><em>Confirm your<br/>orders and<br/>pay it!</em></h1></div><div v-if="cart.length" class="cart-list"><article v-for="(p,i) in checkoutItems" :key="i + '-' + p.id"><img :src="cartImage(p)" :alt="p.name"/><div><strong>{{ p.id === 2 ? 'Basket Socks' : p.id === 5 ? 'Sleeve' : p.id === 4 ? 'Wave Basketball' : p.name }}</strong><b>{{ p.price }}</b></div></article><button class="pay-button transition duration-200 hover:brightness-110 active:scale-95" @click="payOrder">Pay</button></div><div v-else class="empty-cart"><ShoppingCart :size="42"/><h2>Your cart is empty</h2><p>Find your next game-day essential.</p><button class="pay-button" @click="go('home')">Go shopping</button></div></div></main>

    <main v-else-if="screen === 'profile'" class="profile-page"><button class="back-pill" @click="go('home')"><ArrowLeft :size="22"/> BACK</button><div class="outline-ball profile-ball-one"></div><div class="outline-ball profile-ball-two"></div><div class="profile-card"><img class="profile-avatar" src="/images/profile-avatar.jpg" alt="Basketball avatar"/><div class="profile-data"><strong>NAME</strong><strong>NICK-NAME</strong><strong>ADDRESSES</strong><strong>ORDERS</strong><span>Rakh</span><span>MIR</span><span>District 32/1</span><span>24</span></div><button class="profile-edit" @click="go('login')">EDIT PROFILE <ArrowRight :size="15"/></button></div></main>

    <main v-else-if="screen === 'login' || screen === 'register'" :class="['auth-page', screen === 'register' ? 'auth-register' : 'auth-login']"><div class="auth-bg"></div><form class="auth-glass" @submit.prevent="go('home')"><input type="email" placeholder="Email" required/><input type="password" placeholder="Password" required/><input v-if="screen === 'register'" type="password" placeholder="Confirm password" required/><button class="auth-submit transition duration-200 hover:brightness-110 active:scale-95 focus-visible:outline focus-visible:outline-4 focus-visible:outline-offset-4 focus-visible:outline-blue-400">{{ screen === 'login' ? 'Login' : 'Register' }}</button><button v-if="screen === 'login'" class="auth-switch" type="button" @click="go('register')">Create account</button></form></main>

    <main v-else-if="screen === 'about'" class="blue-info-page about-info"><button class="close-info" aria-label="Close" @click="go('home')"><X :size="27"/></button><img class="info-mark" src="/images/combasket-mark-white.png" alt="COMBASKET"/><div class="info-ball-stack"><div v-for="n in 4" :key="n" class="outline-ball"></div></div><p><strong>COMBASKET</strong> is a basketball-focused brand driven by passion for the game.<br/>We design basketballs and equipment that combine performance, durability, and modern style. Inspired by street and professional basketball culture, <strong>COMBASKET</strong> is created for players who demand quality and confidence on every court.</p></main>

    <main v-else-if="screen === 'tech'" class="blue-info-page tech-info"><button class="close-info" aria-label="Close" @click="go('home')"><X :size="27"/></button><div class="tech-copy"><p>At <strong>COMBASKET</strong>, technology is built around the game. Every basketball and piece of equipment is developed using advanced materials and precise manufacturing processes to ensure consistent performance on the court. Our balls feature optimized surface textures for enhanced grip, improved air retention for stable bounce, and reinforced layers for long-lasting durability.</p><p>We test our products in real game conditions — on street courts and indoor arenas — to achieve the perfect balance between control, comfort, and resilience. By combining modern engineering with basketball culture, <strong>COMBASKET</strong> delivers gear that performs when it matters most.</p></div></main>

    <main v-else-if="screen === 'collection'" class="blue-info-page collection-info"><button class="close-info" aria-label="Close" @click="go('home')"><X :size="27"/></button><p>This collection represents the next level of <strong>COMBASKET</strong> quality. Enhanced materials, improved durability, and refined control deliver a better feel and longer performance on every court.</p><div class="collection-story-images"><img src="/images/leggings.jpg" alt="Knee support detail"/><img src="/images/socks.jpg" alt="Basketball socks detail"/><img src="/images/apparel.jpg" alt="Basketball apparel"/></div></main>

    <main v-else class="support-page"><button class="close-info" aria-label="Close" @click="go('home')"><X :size="27"/></button><div class="faq-list"><h1>FAQ</h1><h2>How long does delivery take?</h2><h2>Are COMBASKET balls suitable for outdoor courts?</h2><h2>How can I return a product?</h2><h2>How do I take care of my basketball?</h2></div><div class="zigzag"><span v-for="n in 5" :key="n"></span></div><div class="support-links"><button>Order &amp; Shipping</button><button>Returns &amp; Warranty</button><button>Product Care</button><button>Sizing Guide</button><button>Contact Us</button></div></main>
    <div v-if="paying" class="loading-overlay" role="status" aria-live="polite"><div class="loading-card"><span class="loading-spinner"></span><span>Please Wait</span></div></div>
    <aside v-if="cartOpen" class="mini-cart-overlay" @click.self="cartOpen = false"><section class="mini-cart"><button class="mini-cart-close" aria-label="Close cart" @click="cartOpen = false"><X :size="22"/></button><article v-for="(p,i) in cart" :key="i + '-' + p.id" class="mini-cart-item"><img :src="cartImage(p)" :alt="p.name"/><div class="mini-cart-product"><strong>{{ p.id === 4 ? 'Wave Ball' : p.id === 2 ? 'Basket Socks' : p.id === 5 ? 'Sleeve' : p.name }}</strong><div><b>{{ p.price }}</b><span>₸</span></div></div><button aria-label="Edit item"><Pencil :size="16"/></button><button aria-label="Remove item" @click="cart.splice(i,1)"><Trash2 :size="16"/></button><button aria-label="Select item"><CircleCheck :size="17"/></button></article><button class="mini-cart-buy transition duration-200 hover:brightness-110 active:scale-95" :disabled="!cart.length" @click="cartOpen = false; go('cart')">Buy</button></section></aside>
  </div>
</template>
